spring.application.name=demo
spring.ai.openai.api-key=${OPENAI_API_KEY}
management.endpoints.web.exposure.include=health,metrics,prometheus
management.observations.key-values.enabled=true
management.metrics.enable.gen_ai=true

spring.ai.chat.observations.log-prompt=true
spring.ai.chat.observations.log-completion=true
spring.ai.vectorstore.observations.log-query-response=true
